version = 1

[install]
bun.pkg-path = "bun"
bun.version = "1.1.42"
turbo.pkg-path = "turbo"
turbo.version = "2.3.3"

[hook]
on-activate = '''
  echo "📦 Installing dependencies..."
  bun install --frozen-lockfile
'''

[options]
systems = ["aarch64-darwin", "aarch64-linux", "x86_64-darwin", "x86_64-linux"]
