name: CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  check:
    name: Check code
    runs-on: ubuntu-latest
    steps:
      - name: Access repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: package.json

      - name: Install dependencies
        run: bun install --frozen-lockfile
        env:
          NPM_TOKEN_DEEPDISH: ${{ secrets.NPM_TOKEN_DEEPDISH }}
          NPM_TOKEN_DEEPDISH_CLOUD: ${{ secrets.NPM_TOKEN_DEEPDISH_CLOUD }}

      - name: Analyze code
        run: bun biome ci .

      - name: Check manifest sorting
        run: bun run sort-manifests --check

      - name: Check spelling
        run: bun cspell --dot .

  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Access repo
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: package.json

      - name: Install dependencies
        run: bun install --frozen-lockfile
        env:
          NPM_TOKEN_DEEPDISH: ${{ secrets.NPM_TOKEN_DEEPDISH }}
          NPM_TOKEN_DEEPDISH_CLOUD: ${{ secrets.NPM_TOKEN_DEEPDISH_CLOUD }}

      - name: Run tests
        run: bun test --coverage
