name: CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  check:
    name: Check code
    runs-on: ubuntu-latest
    steps:
      - name: Access repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Analyze code
        run: pnpm biome ci .

      - name: Check manifest sorting
        run: pnpm run sort-manifests --check

      - name: Check spelling
        run: pnpm cspell --dot .

  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Access repo
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run tests
        run: pnpm test --coverage
