name: CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  check:
    name: Check code
    runs-on: ubuntu-latest
    steps:
      - name: Access repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: package.json

      - name: Run code check
        run: bun run ci:check
