name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Access repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: package.json

      - name: Install dependencies
        run: bun install --frozen-lockfile
        env:
          NPM_TOKEN_DEEPDISH: ${{ secrets.NPM_TOKEN_DEEPDISH }}
          NPM_TOKEN_DEEPDISH_CLOUD: ${{ secrets.NPM_TOKEN_DEEPDISH_CLOUD }}

      - name: Apply changesets action
        uses: changesets/action@v1
        with:
          commit: ${{ env.MESSAGE }}
          createGithubReleases: true
          publish: bun ci:publish
          title: ${{ env.MESSAGE }}
          version: bun ci:version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "chore(repo): version workspaces"
          NPM_TOKEN: ${{ secrets.NPM_TOKEN_DEEPDISH }}
          NPM_TOKEN_DEEPDISH_CLOUD: ${{ secrets.NPM_TOKEN_DEEPDISH_CLOUD }}
